### ISSUE TITLE
Addin Error - Relationship Matrix

### ISSUE THREAD

**Issue by njmaeff** [Helmut-Ortmann/EnterpriseArchitect_hoTools#4]
I receive the following error when creating relationships in the relationship matrix:

![capture](https://user-images.githubusercontent.com/31554476/30807593-6964b24a-a1af-11e7-967a-3be272c3bec1.PNG)

The elements are requirements and one user story. The elements have not been added to a diagram and they are all under the same package.

![capture2](https://user-images.githubusercontent.com/31554476/30807647-a3730414-a1af-11e7-9fe8-1d4110e4cd26.PNG)

EA Version 13.5.1351

**Comment by Helmut-Ortmann** [comment]
Hi,

thanks for reporting the issue. Next time, could you please insert the release of hoTools.

I remember, I have fixed something along the exception you showed. With the current hoTools release I couldn't reproduce the issue. Maybe you send me a little repository and your config file (c:\Users\<yourUser>\AppData\Roaming\ho\hoTools\user.config) so that I can reproduce it.

I've just published 3.1.7 with some minor improvement around create new connector via Relationship Matrix. Maybe this helps.

If the issue remains try:

- File,  Reset Factory Settings
- Restart EA
- Give it a new try

Kind regards,

Helmut

**Comment by njmaeff** [comment]
Hi Helmut,

My apologies, I did not have the most updated version. My error was that I downloaded the master branch and installed hoTools that way, it looks like it was Release 2.0.1.0. I uninstalled this release and downloaded/installed the updated version under the Releases tab, the error is no longer showing up.

These are fantastic tools, thank you very much.

Cheers,
